server:
  aws:
    ec2:
      default-credential: "default"

    credentials:

      default:
        access-key-id: "1234"
        secret-access-key: "4321"

      alternative:
        access-key-id: "2345"
        secret-access-key: "5432"