server:

  undertow:
    io-threads: -1
    worker-threads: -1
    buffer-size: 16384

    server-options:
      ENABLE_STATISTICS: false
      RECORD_REQUEST_START_TIME: false
      ALWAYS_SET_KEEP_ALIVE: true

    socket-options:
      BACKLOG: 10000

  static:
    enabled: true

  routes:
    auto-redirect-http-to-https: true

    rewrite:
      -
        virtual-host: "test.localdomain"
        path: "/admin/{something}"
        to: "/test/{something}/admin"
      -
        path: "/admin/{something}"
        to: "/test/{something}/admin"
      -
        virtual-host: "test.localdomain"
        to: "/test/{something}/admin"
      -
        to: "/test/{something}/admin"
      -
        path: "/{domain}-{action}.jsp?id={id}"
        to: "/{domain}/{id}/{action}/"

    reverse:
      - path: "/{domain}-{action}.jsp?id={id}"
        to: "http://localhost:8765"
