server:
  http:
    port: 19999

  urouting:
    content-type-priority: "REQUEST"

  smart-routes:
    auth:
      enabled: true
    cors:
      enabled: true
      always-allow-origin: true
      always-allow-credentials: false
      allowed-methods:
       - "GET"
       - "POST"
       - "PUT"
       - "DELETE"
       - "PATCH"

  auth:
    auth-mechanisms:
      default: kikaha.urouting.it.context.FixedAuthenticationMechanism
    form-auth:
      login-page: "/it/form-auth/login-page"
      callback-url: "/it/form-auth/callback"
    #authentication-request-matcher: kikaha.core.modules.security.ByPassAuthenticationRequestMatcher
    rules:
      - { pattern: "/it/parameters/contextual/*", auth-mechanisms: ["default"] }
      - { pattern: "/it/form-auth/*", auth-mechanisms: ["form"] }
