server:
  http:
    port: 19999

  urouting:
    content-type-priority: "REQUEST"

  smart-routes:
    cors:
      enabled: true
      always-allow-origin: true
      always-allow-credentials: false
      allowed-methods:
       - "GET"
       - "POST"
       - "PUT"
       - "DELETE"
       - "PATCH"

  auth:
    auth-mechanisms:
      default: kikaha.urouting.it.context.FixedAuthenticationMechanism
    rules:
      - { pattern: "/it/parameters/contextual/*", auth-mechanisms: ["default"] }
